### ISSUE TITLE
crash report after hitting reset in fleet controller formspec

### ISSUE THREAD

**Issue by SwissalpS** [S-S-X/jumpdrive#5]
AsyncErr: ServerThread::run Lua: Runtime error from mod '' in callback node_on_receive_fields(): ...test/pandora/minetest/bin/../mods/jumpdrive/formspec.lua:57: attempt to get length of local 'jump_list' (a nil value)
stack traceback:
	...test/pandora/minetest/bin/../mods/jumpdrive/formspec.lua:57: in function 'update_formspec'
	...dora/minetest/bin/../mods/jumpdrive/fleet_controller.lua:76: in function <...dora/minetest/bin/../mods/jumpdrive/fleet_controller.lua:55>

**Comment by S-S-X** [comment]
happens because digiline sets meta "active" to 1 but does not serialize "jump_list" meta.
therefore when "active" is 1 and reset button is pressed it tries to deserialize empty "jump_list" which results in nil and then tries to get length of nil.

Possible fixes:
* use something other than "active" meta for digilines.
   if this then it will not show infotext "Controller active 2 / 4" and wont show stop button
   but could show some banner "Digiline operation in progress"
* serialize engine_pos_list to "jump_list" before setting "active" to 1
   if this then it will show infotext "Controller active 2 / 4" and stop button
   but stop button wont work right away.
   it could be made functional through checking for meta "active" in each async cycle and letting
   that meta value to abort async operation. Causes fleet to stop any process before completion.

Allow stopping or disable formspec while long running digiline operations are in progress?
